apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc01
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage