apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-postgre
  namespace: short-link
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain