apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress01
  annotations:
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: master1.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: short-link-cluster-ip
            port:
              number: 80
