apiVersion: v1
kind: Service
metadata:
  name: short-link-api-cluster-ip
  namespace: short-link
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
  selector:
    components: back-api