apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-link-api-deploy
  namespace: short-link
spec:
  replicas: 1
  selector:
    matchLabels:
      components: back-api
  template:
    metadata:
      labels:
        components: back-api
    spec:
      containers:
      - name: short-link-api
        image: bazdoc/short-link-api:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: api-secret01
                key: DATABASE_URL   
        volumeMounts:
          - name: cm-volume
            mountPath: /etc/test_cm
            readOnly: true
      volumes:
        - name: cm-volume
          configMap:
            name: cm01