apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-link-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgresv16
        image: postgres:16
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        env:
          - name: POSTGRES_DB
            value: db01
          - name: POSTGRES_USER
            value: user01
          - name: POSTGRES_PASSWORD
            value: password123
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc01