apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-link-postgres
  namespace: short-link
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgresv16
        image: postgres:16.0
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: pg-secret01
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pg-secret01
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-secret01
                key: POSTGRES_PASSWORD
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc01
 